import { useParams, Link, useLocation } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { Copy, Check, Building2, MapPin, Globe, Mail, MessageCircle, FileDown } from 'lucide-react';
import { useState, useEffect } from 'react';
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from '../../components/ui/breadcrumb';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card';
import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../../components/ui/table';
import { countriesData } from '../../data/mockData';
import { AdSense } from '../../components/AdSense';
import { SEO } from '../../components/SEO';
import { getSwiftCodesByBank, SwiftCodeDoc } from '../../lib/firebaseQueries';

export function BankSwift() {
  const { countrySlug, bankSlug } = useParams<{ countrySlug: string; bankSlug: string }>();
  const location = useLocation();
  const [copied, setCopied] = useState<string | null>(null);
  const [branches, setBranches] = useState<SwiftCodeDoc[]>([]);
  const [loading, setLoading] = useState(true);

  const country = countriesData.find(c => c.slug === countrySlug);
  const bankNameStr = location.state?.realBankName || bankSlug?.replace(/-/g, ' ');

  useEffect(() => {
    if (country?.code && bankNameStr) {
      setLoading(true);
      getSwiftCodesByBank(country.code, bankNameStr).then(data => {
        setBranches(data);
        setLoading(false);
      });
    }
  }, [country, bankNameStr]);

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(text);
    setTimeout(() => setCopied(null), 2000);
  };

  if (!country || !bankSlug) return <div className="p-12 text-center text-xl text-slate-500 dark:text-slate-400">Bank not found</div>;

  // Derive the head office SWIFT code (usually ends with XXX or is 8 chars, fallback to first in list)
  const headOfficeSwiftDoc = branches.find(b => b.bic && (b.bic.endsWith('XXX') || b.bic.length === 8)) || branches[0];
  const fallbackSwift = (country.code + 'XXXXXX').padEnd(8, 'X');
  const primaryBic = headOfficeSwiftDoc?.bic || fallbackSwift;

  // Anatomy
  const bankCode = primaryBic.substring(0, 4);
  const countryCode = primaryBic.substring(4, 6);
  const locationCode = primaryBic.length >= 8 ? primaryBic.substring(6, 8) : 'XX';
  const headOfficeBranch = primaryBic.length === 11 ? primaryBic.substring(8, 11) : 'XXX';

  const shareText = `Bank Name: ${bankNameStr}\nCountry: ${country.name}\nPrimary SWIFT/BIC Code: ${primaryBic}\n\nFind more details at: ${window.location.href}`;

  const handleCopyAll = () => {
    navigator.clipboard.writeText(shareText);
    setCopied('all');
    setTimeout(() => setCopied(null), 2000);
  };

  const handleWhatsAppShare = () => {
    window.open(`https://wa.me/?text=${encodeURIComponent(shareText)}`, '_blank');
  };

  const handleEmailShare = () => {
    window.location.href = `mailto:?subject=${encodeURIComponent(`SWIFT Code Details for ${bankNameStr}`)}&body=${encodeURIComponent(shareText)}`;
  };

  const handleDownloadPDF = () => {
    import('jspdf').then(({ default: jsPDF }) => {
      const doc = new jsPDF();
      
      doc.setFontSize(22);
      doc.text(`${bankNameStr} SWIFT Details`, 20, 30);
      
      doc.setFontSize(14);
      doc.text(`Country: ${country.name}`, 20, 45);
      
      doc.setFontSize(12);
      doc.text(`Primary SWIFT/BIC Code:`, 20, 60);
      
      doc.setFontSize(20);
      doc.setTextColor(0, 51, 153); // #003399
      doc.text(primaryBic, 20, 70);
      
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(14);
      doc.text(`SWIFT / BIC Code Breakdown:`, 20, 90);
      
      doc.setFontSize(12);
      doc.text(`Bank Code: ${bankCode}`, 20, 100);
      doc.text(`Country Code: ${countryCode}`, 20, 110);
      doc.text(`Location Code: ${locationCode}`, 20, 120);
      doc.text(`Branch Code: ${headOfficeBranch}`, 20, 130);

      if (branches && branches.length > 0) {
        doc.setFontSize(14);
        doc.text(`Additional Branches:`, 20, 150);
        doc.setFontSize(10);
        let yPos = 160;
        branches.slice(0, 15).forEach((b) => {
          doc.text(`${b.bic} - ${b.city || 'N/A'} - ${b.branch || 'Head Office'}`, 20, yPos);
          yPos += 7;
        });
        if (branches.length > 15) {
           doc.text(`... and ${branches.length - 15} more branches.`, 20, yPos);
        }
      }
      
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text(`Generated by SwiftCodeDir - ${window.location.host}`, 20, 280);
      
      doc.save(`${bankNameStr.replace(/\s+/g, '_')}_SWIFT.pdf`);
    });
  };

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "BankOrCreditUnion",
    "name": bankNameStr,
    "address": {
      "@type": "PostalAddress",
      "addressCountry": country.code
    },
    "identifier": {
      "@type": "PropertyValue",
      "propertyID": "SWIFT Code",
      "value": primaryBic
    }
  };

  return (
    <main className="max-w-7xl mx-auto px-4 py-8">
      <SEO 
        title={`${bankNameStr} SWIFT / BIC Codes in ${country.name} | SwiftCodeDir`}
        description={`Find all SWIFT and BIC codes for ${bankNameStr} in ${country.name}. Check branch details, head office code, and more.`}
        canonicalUrl={window.location.href}
      />
      <Helmet>
        <script type="application/ld+json">
          {JSON.stringify(jsonLd)}
        </script>
      </Helmet>

      <Breadcrumb className="mb-8">
        <BreadcrumbList>
          <BreadcrumbItem>
            <BreadcrumbLink href="/">Home</BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbLink href="/swift">SWIFT</BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbLink href={`/swift/${countrySlug}`}>{country.name}</BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbPage className="capitalize">{bankNameStr}</BreadcrumbPage>
          </BreadcrumbItem>
        </BreadcrumbList>
      </Breadcrumb>
      
      <div className="flex items-start justify-between mb-10">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <Building2 className="w-8 h-8 text-[#003399] dark:text-blue-400" />
            <h1 className="text-4xl font-bold text-slate-900 dark:text-slate-100 capitalize">{bankNameStr} SWIFT Codes</h1>
          </div>
          <p className="text-lg text-slate-600 dark:text-slate-400 flex items-center gap-2">
            <MapPin className="w-4 h-4" /> 
            <Link to={`/swift/${countrySlug}`} className="hover:underline hover:text-slate-900 dark:hover:text-slate-200">
              {country.name}
            </Link>
            {/* Assume all listed banks here can receive intl transfers */}
            <Badge variant="outline" className="ml-2 bg-green-50 text-green-700 border-green-200">SEPA Ready</Badge>
          </p>
        </div>
      </div>

      <div className="grid lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-8">
          
          <Card className="border shadow-sm overflow-hidden border-[#003399]/20 dark:border-blue-800/40">
            <div className="h-2 bg-[#003399] dark:bg-blue-600 w-full" />
            <CardContent className="p-8 bg-card dark:bg-slate-950">
              <h2 className="text-sm uppercase tracking-widest font-semibold text-slate-500 dark:text-slate-400 mb-2">
                {loading ? 'Loading Primary Code...' : 'Primary SWIFT / BIC Code'}
              </h2>
              <div className="flex items-center justify-between bg-slate-50 dark:bg-slate-900 p-6 rounded-xl border dark:border-slate-800">
                <div className="font-mono text-4xl font-bold tracking-[0.2em] text-[#003399] dark:text-blue-400">
                  {primaryBic}
                </div>
                <Button 
                  variant="outline" 
                  onClick={() => handleCopy(primaryBic)}
                  className="gap-2"
                >
                  {copied === primaryBic ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
                  {copied === primaryBic ? 'Copied' : 'Copy'}
                </Button>
              </div>

              {/* Action Buttons */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-6 print:hidden">
                <Button variant="secondary" className="w-full gap-2 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200" onClick={handleCopyAll}>
                  {copied === 'all' ? <Check className="w-4 h-4 text-green-600 dark:text-green-400" /> : <Copy className="w-4 h-4" />}
                  {copied === 'all' ? 'Copied Details' : 'Copy All Details'}
                </Button>
                <Button variant="secondary" className="w-full gap-2 bg-[#25D366]/10 dark:bg-[#25D366]/20 text-[#25D366] hover:bg-[#25D366]/20 dark:hover:bg-[#25D366]/30" onClick={handleWhatsAppShare}>
                  <MessageCircle className="w-4 h-4" />
                  WhatsApp
                </Button>
                <Button variant="secondary" className="w-full gap-2 bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-400 hover:bg-blue-200 dark:hover:bg-blue-900/50" onClick={handleEmailShare}>
                  <Mail className="w-4 h-4" />
                  Email Client
                </Button>
                <Button variant="secondary" className="w-full gap-2 bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-400 hover:bg-purple-200 dark:hover:bg-purple-900/50" onClick={handleDownloadPDF}>
                  <FileDown className="w-4 h-4" />
                  Save as PDF
                </Button>
              </div>

              {/* Interactive Map Embed */}
              <div className="mt-8 rounded-xl overflow-hidden border border-slate-200 dark:border-slate-800 shadow-sm print:hidden">
                <div className="bg-slate-50 dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 p-3 flex items-center justify-between">
                  <div className="font-semibold text-sm flex items-center gap-2">
                    <MapPin className="w-4 h-4 text-blue-600" />
                    Find branches nearby
                  </div>
                  <Button variant="outline" size="sm" onClick={() => window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(bankNameStr + " " + country.name)}`, '_blank')} className="h-8 text-xs">
                    Open in Maps
                  </Button>
                </div>
                <iframe 
                  width="100%" 
                  height="250" 
                  frameBorder="0" 
                  scrolling="no" 
                  marginHeight={0} 
                  marginWidth={0} 
                  loading="lazy"
                  src={`https://maps.google.com/maps?width=100%25&height=250&hl=en&q=${encodeURIComponent(bankNameStr + " " + country.name)}&t=&z=12&ie=UTF8&iwloc=B&output=embed`}
                  className="grayscale-[20%] opacity-90 hover:grayscale-0 hover:opacity-100 transition-all duration-500"
                />
              </div>

              <div className="mt-8">
                <h3 className="font-semibold text-slate-900 dark:text-slate-100 mb-4">SWIFT / BIC Code Breakdown</h3>
                <div className="grid grid-cols-4 gap-3 text-center text-sm">
                  <div className="bg-blue-50/80 dark:bg-blue-950/40 p-4 rounded-xl border border-blue-100 dark:border-blue-900 shadow-sm transition-all hover:-translate-y-1 hover:shadow-md">
                    <div className="font-mono font-bold text-2xl text-blue-900 dark:text-blue-400 mb-1">{bankCode}</div>
                    <div className="text-blue-700 dark:text-blue-300 font-medium text-[11px] sm:text-xs uppercase tracking-wider">Bank Code</div>
                    <div className="text-blue-600/70 dark:text-blue-400/70 text-[10px] mt-1 hidden sm:block">4 letters</div>
                  </div>
                  <div className="bg-emerald-50/80 dark:bg-emerald-950/40 p-4 rounded-xl border border-emerald-100 dark:border-emerald-900 shadow-sm transition-all hover:-translate-y-1 hover:shadow-md">
                    <div className="font-mono font-bold text-2xl text-emerald-900 dark:text-emerald-400 mb-1">{countryCode}</div>
                    <div className="text-emerald-700 dark:text-emerald-300 font-medium text-[11px] sm:text-xs uppercase tracking-wider">Country</div>
                    <div className="text-emerald-600/70 dark:text-emerald-400/70 text-[10px] mt-1 hidden sm:block">2 letters</div>
                  </div>
                  <div className="bg-purple-50/80 dark:bg-purple-950/40 p-4 rounded-xl border border-purple-100 dark:border-purple-900 shadow-sm transition-all hover:-translate-y-1 hover:shadow-md">
                    <div className="font-mono font-bold text-2xl text-purple-900 dark:text-purple-400 mb-1">{locationCode}</div>
                    <div className="text-purple-700 dark:text-purple-300 font-medium text-[11px] sm:text-xs uppercase tracking-wider">Location</div>
                    <div className="text-purple-600/70 dark:text-purple-400/70 text-[10px] mt-1 hidden sm:block">2 chars</div>
                  </div>
                  <div className="bg-amber-50/80 dark:bg-amber-950/40 p-4 rounded-xl border border-amber-100 dark:border-amber-900 shadow-sm transition-all hover:-translate-y-1 hover:shadow-md">
                    <div className="font-mono font-bold text-2xl text-amber-900 dark:text-amber-400 mb-1">{headOfficeBranch}</div>
                    <div className="text-amber-700 dark:text-amber-300 font-medium text-[11px] sm:text-xs uppercase tracking-wider">Branch</div>
                    <div className="text-amber-600/70 dark:text-amber-400/70 text-[10px] mt-1 hidden sm:block">3 chars</div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          <div className="space-y-4">
            <h2 className="text-2xl font-bold text-slate-900 dark:text-slate-100">
              {loading ? 'Loading branches...' : 'All Branch Codes'}
            </h2>
            <Card className="overflow-hidden">
              <Table>
                <TableHeader className="bg-slate-50/50 dark:bg-slate-900/50">
                  <TableRow>
                    <TableHead>SWIFT / BIC</TableHead>
                    <TableHead>City</TableHead>
                    <TableHead>Branch Name</TableHead>
                    <TableHead className="w-[100px]"></TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {loading && (
                    <TableRow>
                      <TableCell colSpan={4} className="text-center text-slate-500 py-8">Loading from database...</TableCell>
                    </TableRow>
                  )}
                  {!loading && branches.length === 0 && (
                    <TableRow>
                      <TableCell colSpan={4} className="text-center text-slate-500 py-8">No branches found in database.</TableCell>
                    </TableRow>
                  )}
                  {!loading && branches.map((branch) => (
                    <TableRow key={branch.bic} className="hover:bg-slate-50/50 dark:hover:bg-slate-900/50">
                      <TableCell className="font-mono font-medium">{branch.bic}</TableCell>
                      <TableCell className="text-slate-700 dark:text-slate-300">{branch.city || 'N/A'}</TableCell>
                      <TableCell className="text-slate-500 dark:text-slate-400">{branch.branch || 'Head Office'}</TableCell>
                      <TableCell>
                        <Button variant="ghost" size="sm" onClick={() => handleCopy(branch.bic)}>
                          {copied === branch.bic ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </Card>
          </div>
        </div>

        <aside className="space-y-6">
          <Card className="bg-slate-50 dark:bg-slate-900/50 dark:border-slate-800">
            <CardHeader>
              <CardTitle className="text-lg">Bank Information</CardTitle>
            </CardHeader>
            <CardContent>
              <dl className="space-y-4 text-sm">
                <div>
                  <dt className="text-slate-500 dark:text-slate-400 mb-1">Full Name</dt>
                  <dd className="font-medium text-slate-900 dark:text-slate-100 capitalize">{bankNameStr}</dd>
                </div>
                <div>
                  <dt className="text-slate-500 dark:text-slate-400 mb-1">Country</dt>
                  <dd className="font-medium text-slate-900 dark:text-slate-100 flex items-center gap-2">
                    <span>{country.flag}</span> 
                    <Link to={`/swift/${countrySlug}`} className="text-[#003399] dark:text-blue-400 hover:underline">
                      {country.name}
                    </Link>
                  </dd>
                </div>
                <div>
                  <dt className="text-slate-500 dark:text-slate-400 mb-1">Network Access</dt>
                  <dd className="font-medium text-slate-900 dark:text-slate-100 flex flex-col gap-2 mt-2">
                    <Badge variant="outline" className="w-fit"><Globe className="w-3 h-3 mr-1"/> SWIFT International</Badge>
                    <Badge variant="outline" className="w-fit"><Check className="w-3 h-3 mr-1 text-green-600"/> SEPA Transfers</Badge>
                  </dd>
                </div>
              </dl>
            </CardContent>
          </Card>
          
          <Card className="border border-blue-200 shadow-sm">
            <CardContent className="p-6">
              <h3 className="font-semibold text-slate-900 dark:text-slate-100 mb-2 capitalize">Transferring money to {bankNameStr}?</h3>
              <p className="text-slate-600 dark:text-slate-400 text-sm mb-4">
                If you are sending an international wire template, make sure to ask your beneficiary for their exact IBAN. You will need both the SWIFT code and the IBAN for a successful transaction.
              </p>
              <Link to="/what-is-an-iban">
                <Button variant="outline" className="w-full text-[#003399] dark:text-blue-400 border-[#003399]/30 dark:border-blue-400/30 hover:bg-blue-50 dark:hover:bg-slate-800">
                  Read IBAN Guide
                </Button>
              </Link>
            </CardContent>
          </Card>
          <AdSense slot="5566778899" />
        </aside>
      </div>
    </main>
  );
}
